const carSeed = [{
    carName: 'Tesla',
    title: 'Tesla Model 3 2021',
    ownerName: 'Tommy', 
    img: 'https://images.turo.com/media/vehicle/images/ZHlvY2BtSkqW0RgrWyRM1A.1440x700.jpg',
    description: 'Long Range Dual Motor option + premium white interior! Wireless Charging Pad Heated front and rear seats. Panoramic sunroof',
    features: ["Automatic transmission", "All-wheel drive", "Bluetooth", "Heated seats", "GPS", "USB input"],
    pricePerDay: 50,
    rating: 5,
    guidelines: 'No pets, smoking, vaping, food or drink in the car during the rental. Any spills, smells, hair or damages to the car will incur heavy cleaning charges, so please keep it neat! No Machine Wash! The car is ceramic coated so machine wash will ruin it is Renter responsible for the charging costs during rental. You can use the Tesla Superchargers and I will bill you for usage in bulk after your rental',
    location: 'Alexandria',
    isAvailable: true,
    dateFrom: "03/28/2023",
    dateTo: "04/04/2023",
    totalTrip: 15,
  },
  {
    carName: 'BMW',
    title: 'BMW 3 Series 2017',
    ownerName: 'Robert', 
    img: 'https://images.turo.com/media/vehicle/images/z_jJfNw2RHOojFiODWlywA.1440x700.jpg',
    description: 'I have just added this wonderful car to my fleet. It is in great condition, well maintained and driving smoothly. I believe you will like it too.',
    features: ['Keyless start', '28 MPG', '4 doors', '5 Seats', 'Rear camera', 'Moonroof', 'Paddle shifters', 'Leather seat', 'Automatic transmission'],
    pricePerDay: 90,
    rating: 5,
    guidelines: 'Save time, make drop-off a breeze, and avoid additional fees by adding this Extra, which allows you to return my car at any fuel level. Price includes up to a full tank of gas. Car seat will be provided for different ages',
    totalTrip: 10,
    dateFrom: "04/28/2023",
    dateTo: "05/04/2023",
    isAvailable: true,
  
    
  },
  {
    carName: 'Jeep',
    title: 'Jeep Grand Cherokee 2018',
    ownerName: 'Don Juan', 
    img: 'https://images.turo.com/media/vehicle/images/PA_45wB0RMymDtEyt7yb3w.1440x700.jpg',
    description: '4x4 Sterling Edition has all the bells and whistles. This Grand Cherokee is a great vehicle that you can take to attend a local business meeting and right after pick up your family and friends and head straight to the snow.',
    features: ['Must be 21+ to book', 'All-wheel drive', 'AUX input', 'Keyless entry', 'Backup camera', 'GPS', 'Toll pass', 'Heated seats', 'Automatic transmission'],
    pricePerDay: 110,
    rating: 5,
    guidelines: 'Child car seat or booster available upon request. Car seat will be provided for different ages. The vehicle will be parked on the street and will be unlocked once you text that you have arrived',
    totalTrip: 25,
    dateFrom: "03/30/2023",
    dateTo: "04/10/2023",
    isAvailable: true, 
     
  },

  { carName: 'Toyota',
    title: 'Toyota Prius c 2014',
    ownerName: 'Jerry', 
    img: 'https://images.turo.com/media/vehicle/images/Ew1FSslrQ9iewHn9AWbEFQ.1440x700.jpg',
    description: 'How would you like to take a trip in the rarest color Prius C? The sunbeam yellow will definitely put a smile on your face :). 2014 Toyota Prius C, great mileage saves you on gas, reliable car. Factory tinted windows make long road trips/driving on a sunny day very breezy and comfortable for both the driver, and fellow passengers! ',
    features: ['All-wheel drive', 'Bluetooth', 'AUX input', 'Backup camera', 'GPS', 'Toll pass', 'Automatic transmission'],
    pricePerDay: 55,
    rating: 5,
    guidelines: 'Pick up and drop off instructions will be messaged through Turo, or texted to your number (If international I also use Whatsapp). Gas: Please fill the tank at the end of your trip. This car ONLY takes regular 87 unleaded gas. Gas is not included with your rental so please bring the vehicle back with a FULL tank of gas (You will receive the car with a full tank as well). Lost items: You are responsible for all items you rent from us during your rental. If you lose an item you rented from us, you would be charged for the item. If you left your belongings in the car, contact me and I can save the items for you.',
    totalTrip: 110,
    dateFrom: "03/30/2023",
    dateTo: "04/10/2023",
    isAvailable: true, 
    
},
{
    carName: 'Toyota',
    title: 'Toyota Corolla 2021',
    ownerName: 'Michael', 
    img: 'https://images.turo.com/media/vehicle/images/I4qlX_vxSqSVcRd30f60Zw.1440x700.jpg',
    description: '2021 Toyota Corolla w/vehicle avoidance safety assist features. 4door sedan with automatic transmission and great fuel mileage. Perfect car for you/your group. Flexible pick up time and drop off times. Car is parked at driveway for easy convenient pickup and dropoff.',
    features: ['USB charger', 'Bluetooth', 'AUX input', 'Backup camera', 'Apple CarPlay', 'Blind spot warning', 'Automatic transmission'],
    pricePerDay: 49,
    rating: 4.5,
    guidelines: 'Car is like new inside so no smoking of any kind, or eating in the vehicle. No pets in the vehicle. Vehicle should be returned as received, minor cleaning is okay. I recommend choosing the zero deductible insurance that way if there is any new damage during your trip you will pay zero out of pocket.',
    totalTrip: 110,
    dateFrom: "03/30/2023",
    dateTo: "04/10/2023",
    isAvailable: true, 
     

},
{
    carName: 'Nissan',
    title: 'Nissan Altima 2022',
    ownerName: 'Kyle', 
    img: 'https://images.turo.com/media/vehicle/images/OefNfbsDRMGAkl-P11iHoQ.1440x700.jpg',
    description: 'This brand new 2022 Nissan Altima SR equipped all wheel drive and ready for the road in any season and for any occasion featuring freshly tinted windows to keep you cool in the summer and out the sun with an 8 speed automatic transmission with paddle shift sport mode capable custom leather seats Bluetooth WiFi capable backup camera 29 MPG touch screen display come enjoy the comfort and reliability in this fun gas friendly vehicle we have a strict no smoking and no pet policy there will be a $250 cleaning fee this vehicle will take you wherever you need to go please return on full tank as received or additional fees will be applied to your trip vehicle is equipped with fastrak there will be a $8 fee per crossing thank you for choosing our vehicle we look forward to providing our services to you',
    features: ['Must be 21+ to book', 'USB input', 'USB charger', 'Bluetooth', 'AUX input', 'Backup camera', 'Apple CarPlay', 'Blind spot warning', 'Automatic transmission'],
    pricePerDay: 62,
    rating: 4.78,
    guidelines: 'Car is like new inside so no smoking of any kind, or eating in the vehicle. No pets in the vehicle. Vehicle should be returned as received, minor cleaning is okay. I recommend choosing the zero deductible insurance that way if there is any new damage during your trip you will pay zero out of pocket.',
    totalTrip: 39,
    dateFrom: "03/30/2023",
    dateTo: "04/10/2023",
    isAvailable: true,
     
},

{
    carName: 'Nissan',
    title: 'Nissan Versa 2016',
    ownerName: 'Monica', 
    img: 'https://images.turo.com/media/vehicle/images/87HSl6mXTqyf7h4kMafWZw.1440x700.jpg',
    description: 'This car is well kept,runs very good on gas. This car has wonderful power steering. Very smooth driving. Can do well in city. Compact enough for city parking. Has fast track set up USB capability CD player (nostalgia). Great roomy back seat fits three safely with seat belts Very room trunk.',
    features: ['USB input', 'USB charger', 'Bluetooth', 'AUX input', 'Backup camera', 'Automatic transmission'],
    pricePerDay: 45,
    rating: 4.83,
    guidelines: 'Car is like new inside so no smoking of any kind, or eating in the vehicle. No pets in the vehicle. Vehicle should be returned as received, minor cleaning is okay. I recommend choosing the zero deductible insurance that way if there is any new damage during your trip you will pay zero out of pocket.' ,
    totalTrip: 56,
    dateFrom: "03/30/2023",
    dateTo: "04/10/2023",
    isAvailable: false,
    

},

{
    carName: 'Ford',
    title: 'Ford Mustang 2018',
    ownerName: 'Serhii', 
    img: 'https://images.turo.com/media/vehicle/images/i81BUuOWS--KOnwOht9Atw.1440x700.jpg',
    description: 'Put the top down and enjoy cruising California roads in iconic American triple yellow 2018 Convertible Mustang 2.3L EcoBoost Premium. Enjoy your road trip through North California or explore San Francisco with this amazing pony car.',
    features: ['Must be 21+ to book', 'Keyless entry',' USB input', 'Convertible', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Ventilated seats', 'Backup camera', 'Automatic transmission', 'Heated seats', 'Apple CarPlay', 'Android Auto', 'Digital dashboard'],
    pricePerDay: 85,
    rating: 4.83,
    guidelines: 'Premium 91 Gas Only. Please treat this car as your own. Please respect the rules, drive safely, and bring the car back in the same great shape. Pick-up instructions will be sent after the reservation has been made, usually 1 day before the trip. No smoking or vaping ($250 penalty fee), $150 violation fee for abusive and irresponsible cleaning issues. No Pets ($150 penalty fee), Reckless driving, burnouts, donuts, or racing of any kind are prohibited. You are responsible for any tolls, traffic or parking tickets, and other liabilities during the rental period',
    totalTrip: 69,
    dateFrom: "03/25/2023",
    dateTo: "04/10/2023",
    isAvailable: false,
    
},

{
  carName: 'Mercedes-Benz',
  title: 'Mercedes-Benz CLA-Class 2018',
  ownerName: 'Richie', 
  img: 'https://images.turo.com/media/vehicle/images/TsqjkbxDQiCIqE4njZpOhA.1440x700.jpg',
  description: 'Turbocharged sporty and classy Mercedes-Benz CLA. 37 MPG highway! Great for long trips. Leather and black wood grain interior. Three modes of driving including eco, comfort, and dynamic sport mode. Premium sound system performs at both low and high volumes and speeds. Tinted windows keep you cool and the privacy up. Panoramic moonroof let’s you experience the ride comfortably and in style in California weather.',
  features: ['Must be 21+ to book', 'Tinted Windows', 'Keyless entry',' USB input', 'Convertible', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Ventilated seats', 'Backup camera', 'Automatic transmission', 'Heated seats', 'Apple CarPlay', 'Android Auto', 'Digital dashboard'],
  pricePerDay: 70,
  rating: 4.98,
  guidelines: 'No smoking 🚭. Please be on time when dropping off the vehicle 🕰 , if you would like to modify the booking please let me know as early as possible so that you can be better accommodated. Be careful to not scratch the rims when parking.',
  totalTrip: 71,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
  
},

{
  carName: 'Mercedes-Benz',
  title: 'Mercedes-Benz SLK-Class 2016',
  ownerName: 'Lissa', 
  img: 'https://images.turo.com/media/vehicle/images/LluPZ9tXQO-jgG1vD1JHuQ.1440x700.jpg',
  description: 'First of all, this SLK 300 Roadster is beautiful to look at. The outside of the car is silver with beautiful burgundy leather seats. The droptop is a beautiful hard top or with the touch of a button, it becomes  a fun loving open air roadster. And of course, fundamental to SLK luxury roadsters are the prestige and pampering inherent in Mercedes Benz vehicles. Either way, it coddles you around town, offers a premium driving experience you expect from Mercedes Benz and you will look great in it.',
  features: ['Must be 21+ to book', 'Tinted Windows', 'Keyless entry',' USB input', 'Convertible', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Ventilated seats', 'Backup camera', 'Automatic transmission', 'Heated seats', 'Apple CarPlay', 'Android Auto', 'Digital dashboard'],
  pricePerDay: 90,
  rating: 4.94,
  guidelines: 'Dogs are always welcome. Please return car clean and with a full premium gas.',
  totalTrip: 40,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: false,
  
},

{
  carName: 'Ford',
  title: 'Ford Mustang 2019',
  ownerName: 'Xscape Rentals', 
  img: 'https://images.turo.com/media/vehicle/images/nmNom8RsRxuhpSLt-C4evw.1440x700.jpg',
  description: 'Cherry red Mustang for a classic look. This is the kind of beauty to drive down the coast and enjoy the breeze that comes with driving a muscle car. Take a joy ride in our Mustang that’s seamlessly taken care of for any and all kind of trips that you desire to endeavor on.',
  features: ['Must be 21+ to book', 'Automatic transmission', 'Long-term car'],
  pricePerDay: 75,
  rating: 4.92,
  guidelines: 'If returning earlier/later than pick up/drop off time, guest must give us a 30 minute heads up or will have to wait for our team to receive the vehicle. Keys are not to be left in the vehicle parked under no circumstances. That is an automatic $100 fee for leaving a vehicle unattended. Guests are responsible for the full cost of any key pertaining to the vehicle that is lost/misplaced. NO SMOKING IS PERMITTED. Odor or residue of smoke in the vehicle is a $250 fee. No exceptions. When you park, please follow the traffic of the other vehicles at our parking slot.',
  totalTrip: 90,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
  
},
{
  carName: 'Jeep',
  title: 'Jeep Grand Cherokee 2018',
  ownerName: 'Jonathan', 
  img: 'https://images.turo.com/media/vehicle/images/fKqF9c_oR3afkOXP5ito-g.1440x700.jpg',
  description: 'This truck is the perfect vehicle for you. Jeeps are known for reliability and performance which means that this car is safe to bring you anywhere in comfort and style. Equipped with 4WD, this 3.6L 6Cyl engine would get you 295hp which would get you a lot of power. This incredibly spacious car fits 5 people comfortably and the huge trunk space would allow you to bring a lot of things for your trip! The sound system of this car is out of this world, you can connect through Apple/Android car play or the traditional AUX. This car is the perfect truck for you to utilize for luxury and leisure!',
  features: ['Must be 21+ to book', 'Tinted Windows', 'Keyless entry',' USB input', 'Convertible', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Ventilated seats', 'Backup camera', 'Automatic transmission', 'Heated seats', 'Apple CarPlay', 'Android Auto', 'Digital dashboard'],
  pricePerDay: 80,
  rating: 4.92,
  guidelines: 'NO Smoking of any kind in the car. No Off-Roading in any way. No towing of any sort',
  totalTrip: 12,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
  
},
{
  carName: 'Tesla',
  title: 'Tesla Model 3 2017',
  ownerName: 'Luke', 
  img: 'https://images.turo.com/media/vehicle/images/K1-NMGxER8qj-WYLsX53WQ.1440x700.jpg',
  description: 'This Model 3 - one of the first ever made - makes the journey enjoyable. It is equipped with 260 miles of maximum range, convenient access to the Supercharger network of fast charging stations, Autopilot and Full Self-Driving capability (human supervision required), all-season tires, camping and dog mode climate control settings, and the best built-in navigation system of any car out there. ',
  features: ['Supercharger network access', 'Must be 21+ to book', 'Spotify', 'Keyless entry',' USB input', 'All-season tires with 3-peak snowflake', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Ventilated seats', 'Backup camera', 'Automatic transmission', 'Heated seats', 'Apple CarPlay', 'Android Auto', 'Digital dashboard'],
  pricePerDay: 81,
  rating: 4.95,
  guidelines: 'Pets are welcome, smoking is not. Please return the car with at least 100 miles of range, the more the better. Always pay attention to the road even if the car is on Autopilot, it is still learning how to drive and might need you to retake control at any time (though most of the time it is very good.',
  totalTrip: 47,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: false,
  
},

{
  carName: 'Toyota',
  title: 'Toyota Camry 2019',
  ownerName: 'Xscape Rentals', 
  img: 'https://images.turo.com/media/vehicle/images/z5z9c3KcT02xoKaj1m92HA.1440x700.jpg',
  description: 'This beautiful Toyota Camry is amazingly white from the exterior and cherry red from the interior. This car has a gas saver, and super smooth to drive old a road trip, or even on a short day trip. This at offers an extensive amount of comfort and is perfect for whatever the occasion may be.',
  features: ['USB input', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Backup camera', 'Automatic transmission', 'Blind spot warning', 'Apple CarPlay'],
  pricePerDay: 35,
  rating: 4.84,
  guidelines: 'Guests must provide their own insurance or purchase our fleet insurance in order to pick up the designated vehicle. If returning earlier/later than pick up/drop off time, guest must give us a 30 minute heads up or will have to wait for our team to receive the vehicle.',
  totalTrip: 8190,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
  
},

{
  carName: 'Nissan',
  title: 'Nissan Altima 2013',
  ownerName: 'Brian', 
  img: 'https://images.turo.com/media/vehicle/images/bnhXhmFBQSa4kBsUuQlf_A.1440x700.jpg',
  description: 'i am advertising my 2013 Nissan Altima S2,5 I just purchased it for the turo renters and advertising it for great rides it has Bluetooth, keyless entry, power windows and door locks, Start/Stop and et cetera, it iss great on saving gas and long trips, for protecting my business I am having air tags on my vehicles in case if any stealing car processes the renters get back to me right away I can detect the location of the car, please book my car and enjoy with it thanks :)',
  features: ['USB input', 'Keyless entry', 'GPS', 'Bluetooth', 'AUX input', 'Backup camera', 'Automatic transmission'],
  pricePerDay: 45,
  rating: 5,
  guidelines: 'Guests must provide their own insurance or purchase our fleet insurance in order to pick up the designated vehicle. If returning earlier/later than pick up/drop off time, guest must give us a 30 minute heads up or will have to wait for our team to receive the vehicle.',
  totalTrip: 2,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
  
},

{
  carName: 'Toyota',
  title: 'Toyota Prius 2012',
  ownerName: 'Kashif', 
  img: 'https://images.turo.com/media/vehicle/images/JYSnQzABT06zajz9ag6p1Q.1440x700.jpg',
  description: 'Credited with starting the hybrid craze, the Toyota Prius revolutionized the alternative powertrain by packaging it into a unique, yet practical 5-door. While its styling may be wacky, part of its mass appeal is due to the fact that it operates much like a normal car.',
  features: ['Sunroof', 'USB input', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Backup camera', 'Automatic transmission', 'Blind spot warning', 'Apple CarPlay', 'Child seat', 'Toll pass'],
  pricePerDay: 50,
  rating: 4.74,
  guidelines: 'Please do not smoke in or around the car. If returning earlier/later than pick up/drop off time, 250 miles / day are included in the rental price. $0.50 per extra mile. The car comes with FasTrak. You will be responsible for the toll fees but you can fly through the tolls without stopping rather being frustrated waiting behind the tolls. Car takes 91 octane premium gas ONLY since its LT Model. Upon returning the car, please present your gas receipt to prove premium gas was used.',
  totalTrip: 35,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
  
},


{
  carName: 'Nissan',
  title: 'Nissan Versa',
  ownerName: 'Kashif', 
  img: 'https://images.turo.com/media/vehicle/images/JYSnQzABT06zajz9ag6p1Q.1440x700.jpg',
  description: 'Credited with starting the hybrid craze, the Toyota Prius revolutionized the alternative powertrain by packaging it into a unique, yet practical 5-door. While its styling may be wacky, part of its mass appeal is due to the fact that it operates much like a normal car.',
  features: ['Sunroof', 'USB input', 'USB charger', 'GPS', 'Bluetooth', 'AUX input', 'Backup camera', 'Automatic transmission', 'Blind spot warning', 'Apple CarPlay', 'Child seat', 'Toll pass'],
  pricePerDay: 50,
  rating: 4.74,
  guidelines: 'Please do not smoke in or around the car. If returning earlier/later than pick up/drop off time, 250 miles / day are included in the rental price. $0.50 per extra mile. The car comes with FasTrak. You will be responsible for the toll fees but you can fly through the tolls without stopping rather being frustrated waiting behind the tolls. Car takes 91 octane premium gas ONLY since its LT Model. Upon returning the car, please present your gas receipt to prove premium gas was used.',
  totalTrip: 35,
  dateFrom: "03/18/2023",
  dateTo: "04/10/2023",
  isAvailable: true,
},

];


module.exports = carSeed